/**
 * GadgetWallet Bangladesh catalog dataset.
 *
 * Exactly the six categories + 60 products defined in
 * docs/GadgetWallet_Bangladesh_Product_Migration_Guide.md. Prices are BDT,
 * image filenames match docs/GadgetWallet_60_Product_Image_Search_Links.md so
 * real photos can be dropped into assets/product-images/ later and swapped in
 * with scripts/upload-catalog-images.ts.
 *
 * Data only — no application logic lives here.
 */

export interface CatalogCategory {
  name: string;
  slug: string;
  description: string;
}

export interface CatalogBrand {
  name: string;
  slug: string;
  description: string;
}

export interface CatalogProduct {
  name: string;
  brandSlug: string;
  categorySlug: string;
  model: string;
  /** Price in BDT. */
  price: number;
  /** Discounted price in BDT (optional — drives the Flash Sale section). */
  discountPrice?: number;
  sku: string;
  stock: number;
  rating: number;
  reviewCount: number;
  isFeatured: boolean;
  isNewArrival: boolean;
  isBestSeller: boolean;
  /** Filename from the image search-links doc, e.g. "baseus-bipow-10000mah.webp". */
  imageFile: string;
  color?: string;
  /** Feature bullets appended to the auto-built full description. */
  highlights: string[];
  /** Category-specific specs (capacity, connector, compatibility, ...). */
  specs: { key: string; value: string }[];
  shortDescription: string;
}

export const CATEGORIES: CatalogCategory[] = [
  {
    name: "Earphone",
    slug: "earphone",
    description: "Wired earphones with clear sound from top brands, available across Bangladesh.",
  },
  {
    name: "Power Bank",
    slug: "power-bank",
    description: "Fast-charging power banks from 10,000mAh to 20,000mAh for every phone.",
  },
  {
    name: "USB Cable",
    slug: "usb-cable",
    description: "Durable USB-C, Micro USB and Lightning cables with fast charging support.",
  },
  {
    name: "Glass Protector",
    slug: "glass-protector",
    description: "9H tempered glass screen protectors for popular phone models.",
  },
  {
    name: "Earbuds",
    slug: "earbuds",
    description: "Wireless earbuds with deep bass, ANC and long battery life.",
  },
  {
    name: "Smart Watch",
    slug: "smart-watch",
    description: "Fitness and calling smart watches for every lifestyle.",
  },
];

export const BRANDS: CatalogBrand[] = [
  { name: "Xiaomi", slug: "xiaomi", description: "Xiaomi official accessories and wearables" },
  { name: "Redmi", slug: "redmi", description: "Redmi by Xiaomi — budget audio and power" },
  { name: "Realme", slug: "realme", description: "Realme official audio and wearables" },
  { name: "Baseus", slug: "baseus", description: "Baseus tech lifestyle accessories" },
  { name: "Hoco", slug: "hoco", description: "Hoco mobile accessories" },
  { name: "Joyroom", slug: "joyroom", description: "Joyroom digital accessories" },
  { name: "Samsung", slug: "samsung", description: "Samsung official audio and wearables" },
  { name: "Anker", slug: "anker", description: "Anker charging and audio technology" },
  { name: "UGREEN", slug: "ugreen", description: "UGREEN connectivity and charging" },
  { name: "Oraimo", slug: "oraimo", description: "Oraimo smart accessories" },
  { name: "QCY", slug: "qcy", description: "QCY wireless audio" },
  { name: "Soundcore", slug: "soundcore", description: "Soundcore by Anker — audio" },
  { name: "Haylou", slug: "haylou", description: "Haylou smart wearables" },
  { name: "Kieslect", slug: "kieslect", description: "Kieslect calling watches" },
  { name: "Amazfit", slug: "amazfit", description: "Amazfit smart wearables" },
  { name: "Generic", slug: "generic", description: "Compatible accessories" },
];

/**
 * 60 products, ordered so the six homepage-featured picks (section 11 of the
 * migration guide) come LAST — the runner assigns created_at in array order
 * and the storefront featured grid orders by created_at DESC (LIMIT 8), which
 * guarantees the six picks appear first on the homepage.
 */
export const PRODUCTS: CatalogProduct[] = [
  // ─────────────────────────── Earphone (stock 30) ───────────────────────────
  {
    name: "Xiaomi Mi In-Ear Basic",
    brandSlug: "xiaomi",
    categorySlug: "earphone",
    model: "Mi In-Ear Basic",
    price: 450,
    sku: "EP-XM-MIIB",
    stock: 30,
    rating: 4.4,
    reviewCount: 128,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "xiaomi-mi-in-ear-basic.webp",
    color: "Black",
    highlights: ["Deep bass with clear vocal reproduction", "Comfortable silicone ear tips", "3.5mm audio jack with in-line microphone"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Xiaomi Mi In-Ear Basic wired earphones with deep bass and in-line mic.",
  },
  {
    name: "Xiaomi Redmi Earphones",
    brandSlug: "xiaomi",
    categorySlug: "earphone",
    model: "Redmi Earphones",
    price: 599,
    sku: "EP-XM-RDMI",
    stock: 30,
    rating: 4.5,
    reviewCount: 210,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "xiaomi-redmi-earphones.webp",
    color: "White",
    highlights: ["Balanced sound with powerful bass", "Lightweight in-ear design", "In-line controls for calls and music"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Xiaomi Redmi Earphones with balanced sound and in-line controls.",
  },
  {
    name: "Realme Buds Classic",
    brandSlug: "realme",
    categorySlug: "earphone",
    model: "Buds Classic",
    price: 550,
    sku: "EP-RM-BCLS",
    stock: 30,
    rating: 4.3,
    reviewCount: 96,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "realme-buds-classic.webp",
    color: "White",
    highlights: ["Premium 11.2mm drivers", "Crystal-clear call quality", "Anti-tangle flat cable"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Realme Buds Classic wired earphones with premium 11.2mm drivers.",
  },
  {
    name: "Baseus Encok H06",
    brandSlug: "baseus",
    categorySlug: "earphone",
    model: "Encok H06",
    price: 699,
    sku: "EP-BS-H06",
    stock: 30,
    rating: 4.4,
    reviewCount: 143,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "baseus-encok-h06.webp",
    color: "Black",
    highlights: ["Magnetic earbud design", "Enhanced bass with HD sound", "Braided tangle-free cable"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Baseus Encok H06 wired earphones with magnetic buds and braided cable.",
  },
  {
    name: "Baseus Encok H18",
    brandSlug: "baseus",
    categorySlug: "earphone",
    model: "Encok H18",
    price: 799,
    discountPrice: 699,
    sku: "EP-BS-H18",
    stock: 30,
    rating: 4.5,
    reviewCount: 167,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "baseus-encok-h18.webp",
    color: "Blue",
    highlights: ["Powerful bass with HD stereo sound", "Ergonomic comfort fit", "In-line microphone for calls"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Baseus Encok H18 stereo earphones with powerful bass and HD sound.",
  },
  {
    name: "Hoco M1 Original",
    brandSlug: "hoco",
    categorySlug: "earphone",
    model: "M1 Original",
    price: 299,
    sku: "EP-HC-M1",
    stock: 30,
    rating: 4.1,
    reviewCount: 88,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "hoco-m1-original.webp",
    color: "Black",
    highlights: ["Value-packed daily earphones", "Comfortable silicone tips", "In-line mic and controls"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Hoco M1 original wired earphones — an everyday budget favourite.",
  },
  {
    name: "Hoco M88",
    brandSlug: "hoco",
    categorySlug: "earphone",
    model: "M88",
    price: 399,
    sku: "EP-HC-M88",
    stock: 30,
    rating: 4.2,
    reviewCount: 74,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "hoco-m88.webp",
    color: "White",
    highlights: ["Clear stereo sound", "Durable braided cable", "Built-in microphone"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Hoco M88 wired earphones with clear stereo sound and braided cable.",
  },
  {
    name: "Joyroom JR-E106",
    brandSlug: "joyroom",
    categorySlug: "earphone",
    model: "JR-E106",
    price: 499,
    sku: "EP-JR-E106",
    stock: 30,
    rating: 4.3,
    reviewCount: 61,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "joyroom-jr-e106.webp",
    color: "Black",
    highlights: ["Balanced sound signature", "Ergonomic in-ear design", "In-line call controls"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Joyroom JR-E106 wired earphones with balanced sound and ergonomic fit.",
  },
  {
    name: "Samsung EO-IA500",
    brandSlug: "samsung",
    categorySlug: "earphone",
    model: "EO-IA500",
    price: 999,
    sku: "EP-SM-IA500",
    stock: 30,
    rating: 4.6,
    reviewCount: 152,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "samsung-eo-ia500.webp",
    color: "White",
    highlights: ["Genuine Samsung tuning", "Comfortable angled fit", "In-line mic with play/pause control"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Samsung & all Android/iOS devices" },
    ],
    shortDescription: "Genuine Samsung EO-IA500 earphones with studio-tuned sound.",
  },

  // ─────────────────────────── Power Bank (stock 20) ─────────────────────────
  {
    name: "Redmi Power Bank 10000mAh",
    brandSlug: "redmi",
    categorySlug: "power-bank",
    model: "Redmi Power Bank 10000mAh",
    price: 1599,
    sku: "PB-RD-10000",
    stock: 20,
    rating: 4.5,
    reviewCount: 320,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "redmi-power-bank-10000mah.webp",
    color: "Black",
    highlights: ["10000mAh capacity", "18W fast charging support", "Dual USB output", "LED battery indicator"],
    specs: [
      { key: "Battery Capacity", value: "10000mAh" },
      { key: "Output", value: "Dual USB 5V/2.4A" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Redmi 10000mAh power bank with 18W fast charging and dual USB output.",
  },
  {
    name: "Mi Power Bank 3 20000mAh",
    brandSlug: "xiaomi",
    categorySlug: "power-bank",
    model: "Mi Power Bank 3 20000mAh",
    price: 2699,
    sku: "PB-XM-MPB3-20000",
    stock: 20,
    rating: 4.7,
    reviewCount: 415,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "mi-power-bank-3-20000mah.webp",
    color: "Black",
    highlights: ["20000mAh high-capacity cell", "18W bidirectional fast charging", "Dual USB + USB-C input", "12-layer safety protection"],
    specs: [
      { key: "Battery Capacity", value: "20000mAh" },
      { key: "Output", value: "Dual USB 5V/2.4A + USB-C" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Mi Power Bank 3 20000mAh with bidirectional 18W fast charging.",
  },
  {
    name: "Baseus Adaman Metal 20000mAh",
    brandSlug: "baseus",
    categorySlug: "power-bank",
    model: "Adaman Metal 20000mAh",
    price: 2999,
    sku: "PB-BS-ADAMAN",
    stock: 20,
    rating: 4.7,
    reviewCount: 189,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "baseus-adaman-20000mah.webp",
    color: "Gray",
    highlights: ["20000mAh capacity", "20W fast charging", "Premium metal alloy body", "USB-C input with quick recharge"],
    specs: [
      { key: "Battery Capacity", value: "20000mAh" },
      { key: "Output", value: "USB-C 20W + Dual USB" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Baseus Adaman 20000mAh metal power bank with 20W fast charging.",
  },
  {
    name: "Anker PowerCore Select 10000mAh",
    brandSlug: "anker",
    categorySlug: "power-bank",
    model: "PowerCore Select 10000mAh",
    price: 2599,
    sku: "PB-ANK-PCS10000",
    stock: 20,
    rating: 4.7,
    reviewCount: 233,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "anker-powercore-select-10000.webp",
    color: "Black",
    highlights: ["10000mAh with PowerIQ fast charging", "Charge an iPhone 15 nearly twice", "Compact portable design", "MultiProtect safety system"],
    specs: [
      { key: "Battery Capacity", value: "10000mAh" },
      { key: "Output", value: "Single USB 5V/2.4A" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Anker PowerCore Select 10000mAh power bank with PowerIQ fast charging.",
  },
  {
    name: "Anker PowerCore Essential 20000mAh",
    brandSlug: "anker",
    categorySlug: "power-bank",
    model: "PowerCore Essential 20000mAh",
    price: 3999,
    sku: "PB-ANK-PCE20000",
    stock: 20,
    rating: 4.8,
    reviewCount: 156,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "anker-powercore-essential-20000.webp",
    color: "Black",
    highlights: ["20000mAh high-capacity charging", "PowerIQ 2.0 fast charging", "Charge two devices at once", "Full recharge in under 7 hours"],
    specs: [
      { key: "Battery Capacity", value: "20000mAh" },
      { key: "Output", value: "Dual USB 5V/2.4A" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Anker PowerCore Essential 20000mAh power bank for multi-day power.",
  },
  {
    name: "Joyroom JR-QP191 10000mAh",
    brandSlug: "joyroom",
    categorySlug: "power-bank",
    model: "JR-QP191 10000mAh",
    price: 1699,
    sku: "PB-JR-QP191",
    stock: 20,
    rating: 4.4,
    reviewCount: 87,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "joyroom-jr-qp191.webp",
    color: "White",
    highlights: ["10000mAh capacity", "Dual USB output", "Slim pocket-friendly body", "LED power indicator"],
    specs: [
      { key: "Battery Capacity", value: "10000mAh" },
      { key: "Output", value: "Dual USB 5V/2.1A" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Joyroom JR-QP191 10000mAh slim power bank with dual USB output.",
  },
  {
    name: "Hoco J72 Easy Travel 10000mAh",
    brandSlug: "hoco",
    categorySlug: "power-bank",
    model: "J72 Easy Travel 10000mAh",
    price: 1399,
    sku: "PB-HC-J72",
    stock: 20,
    rating: 4.3,
    reviewCount: 92,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "hoco-j72-easy-travel.webp",
    color: "White",
    highlights: ["10000mAh capacity", "Lightweight travel design", "Dual USB output", "LED indicator"],
    specs: [
      { key: "Battery Capacity", value: "10000mAh" },
      { key: "Output", value: "Dual USB 5V/2.1A" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Hoco J72 Easy Travel 10000mAh power bank — light, compact and reliable.",
  },
  {
    name: "Hoco J86B 20000mAh",
    brandSlug: "hoco",
    categorySlug: "power-bank",
    model: "J86B 20000mAh",
    price: 2199,
    discountPrice: 1899,
    sku: "PB-HC-J86B",
    stock: 20,
    rating: 4.4,
    reviewCount: 104,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "hoco-j86b-20000mah.webp",
    color: "Black",
    highlights: ["20000mAh capacity", "Fast charging support", "Dual USB output", "Digital display"],
    specs: [
      { key: "Battery Capacity", value: "20000mAh" },
      { key: "Output", value: "Dual USB 5V/2.1A" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Hoco J86B 20000mAh power bank with fast charging and digital display.",
  },
  {
    name: "Oraimo Traveler 3 20000mAh",
    brandSlug: "oraimo",
    categorySlug: "power-bank",
    model: "Traveler 3 20000mAh",
    price: 2499,
    sku: "PB-ORM-T3",
    stock: 20,
    rating: 4.5,
    reviewCount: 131,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "oraimo-traveler-3-20000mah.webp",
    color: "Black",
    highlights: ["20000mAh capacity", "22.5W fast charging", "USB-C and dual USB output", "Smart charging protection"],
    specs: [
      { key: "Battery Capacity", value: "20000mAh" },
      { key: "Output", value: "USB-C 22.5W + Dual USB" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Oraimo Traveler 3 20000mAh power bank with 22.5W fast charging.",
  },

  // ─────────────────────────── USB Cable (stock 40) ─────────────────────────
  {
    name: "Baseus Superior Series USB-C Cable",
    brandSlug: "baseus",
    categorySlug: "usb-cable",
    model: "Superior Series USB-C",
    price: 349,
    sku: "UC-BS-SUPERIOR",
    stock: 40,
    rating: 4.5,
    reviewCount: 201,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "baseus-superior-series-usb-c.webp",
    color: "Black",
    highlights: ["120W fast charging support", "Nylon braided durable body", "Data transfer up to 480Mbps"],
    specs: [
      { key: "Type", value: "USB-C to USB-C" },
      { key: "Length", value: "1m" },
      { key: "Compatibility", value: "USB-C phones, tablets & laptops" },
    ],
    shortDescription: "Baseus Superior Series USB-C cable with 120W fast charging support.",
  },
  {
    name: "Baseus Cafule Series USB-C Cable",
    brandSlug: "baseus",
    categorySlug: "usb-cable",
    model: "Cafule Series USB-C",
    price: 499,
    sku: "UC-BS-CAFULE",
    stock: 40,
    rating: 4.6,
    reviewCount: 176,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "baseus-cafule-series-usb-c.webp",
    color: "Blue",
    highlights: ["100W fast charging", "Double-braided nylon exterior", "Aluminum alloy connectors"],
    specs: [
      { key: "Type", value: "USB-C to USB-C" },
      { key: "Length", value: "1m" },
      { key: "Compatibility", value: "USB-C phones, tablets & laptops" },
    ],
    shortDescription: "Baseus Cafule Series USB-C cable — braided, durable, 100W rated.",
  },
  {
    name: "Anker PowerLine Micro USB Cable",
    brandSlug: "anker",
    categorySlug: "usb-cable",
    model: "PowerLine Micro USB",
    price: 749,
    sku: "UC-ANK-PLMIC",
    stock: 40,
    rating: 4.6,
    reviewCount: 142,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "anker-powerline-micro-usb.webp",
    color: "Black",
    highlights: ["Ultra-durable PowerLine build", "Fast charging for Micro USB devices", "Reinforced stress points"],
    specs: [
      { key: "Type", value: "USB-A to Micro USB" },
      { key: "Length", value: "0.9m" },
      { key: "Compatibility", value: "Micro USB Android devices, speakers & power banks" },
    ],
    shortDescription: "Anker PowerLine Micro USB cable with legendary durability.",
  },
  {
    name: "UGREEN USB-C Fast Charging Cable",
    brandSlug: "ugreen",
    categorySlug: "usb-cable",
    model: "USB-C Fast Charging",
    price: 499,
    discountPrice: 399,
    sku: "UC-UG-CFAST",
    stock: 40,
    rating: 4.5,
    reviewCount: 189,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "ugreen-usb-c-fast-charging.webp",
    color: "Black",
    highlights: ["66W fast charging support", "High-strength braided cable", "Slim reversible USB-C connector"],
    specs: [
      { key: "Type", value: "USB-A to USB-C" },
      { key: "Length", value: "1m" },
      { key: "Compatibility", value: "USB-C phones and tablets" },
    ],
    shortDescription: "UGREEN USB-C fast charging cable with 66W support and braided build.",
  },
  {
    name: "UGREEN Lightning Cable",
    brandSlug: "ugreen",
    categorySlug: "usb-cable",
    model: "Lightning Cable",
    price: 699,
    sku: "UC-UG-LIGHT",
    stock: 40,
    rating: 4.5,
    reviewCount: 118,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    imageFile: "ugreen-lightning-cable.webp",
    color: "White",
    highlights: ["MFi certified Lightning connector", "Fast charging for iPhone and iPad", "Durable woven exterior"],
    specs: [
      { key: "Type", value: "USB-A to Lightning" },
      { key: "Length", value: "1m" },
      { key: "Compatibility", value: "iPhone & iPad with Lightning port" },
    ],
    shortDescription: "UGREEN MFi certified Lightning cable with fast charging support.",
  },
  {
    name: "Joyroom S-CL020A9 Lightning Cable",
    brandSlug: "joyroom",
    categorySlug: "usb-cable",
    model: "S-CL020A9 Lightning",
    price: 499,
    sku: "UC-JR-SCL",
    stock: 40,
    rating: 4.3,
    reviewCount: 76,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "joyroom-s-cl020a9.webp",
    color: "White",
    highlights: ["Apple-certified Lightning connector", "Fast charge and sync", "Tangle-resistant cable"],
    specs: [
      { key: "Type", value: "USB-A to Lightning" },
      { key: "Length", value: "1m" },
      { key: "Compatibility", value: "iPhone & iPad with Lightning port" },
    ],
    shortDescription: "Joyroom S-CL020A9 Lightning cable for fast iPhone charging.",
  },
  {
    name: "Hoco X14 Times Speed USB-C Cable",
    brandSlug: "hoco",
    categorySlug: "usb-cable",
    model: "X14 Times Speed USB-C",
    price: 299,
    sku: "UC-HC-X14",
    stock: 40,
    rating: 4.2,
    reviewCount: 84,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "hoco-x14-times-speed.webp",
    color: "Black",
    highlights: ["Fast charge and data sync", "Sturdy TPU exterior", "Compact and travel friendly"],
    specs: [
      { key: "Type", value: "USB-A to USB-C" },
      { key: "Length", value: "1m" },
      { key: "Compatibility", value: "USB-C Android devices" },
    ],
    shortDescription: "Hoco X14 Times Speed USB-C cable for fast charging on a budget.",
  },
  {
    name: "Hoco X59 Magnificent Lightning Cable",
    brandSlug: "hoco",
    categorySlug: "usb-cable",
    model: "X59 Magnificent Lightning",
    price: 399,
    sku: "UC-HC-X59",
    stock: 40,
    rating: 4.2,
    reviewCount: 67,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "hoco-x59-magnificent.webp",
    color: "White",
    highlights: ["Lightning fast charging", "Slim durable cable", "Plug-and-play sync"],
    specs: [
      { key: "Type", value: "USB-A to Lightning" },
      { key: "Length", value: "1m" },
      { key: "Compatibility", value: "iPhone & iPad with Lightning port" },
    ],
    shortDescription: "Hoco X59 Magnificent Lightning cable for reliable iPhone charging.",
  },
  {
    name: "Realme Type-C VOOC Cable",
    brandSlug: "realme",
    categorySlug: "usb-cable",
    model: "Type-C VOOC Cable",
    price: 499,
    sku: "UC-RM-VOOC",
    stock: 40,
    rating: 4.4,
    reviewCount: 95,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "realme-type-c-vooc-cable.webp",
    color: "Yellow",
    highlights: ["Supports VOOC / SuperVOOC fast charging", "Original Realme accessory", "Durable cable construction"],
    specs: [
      { key: "Type", value: "USB-A to USB-C" },
      { key: "Length", value: "1m" },
      { key: "Compatibility", value: "OPPO, Realme & OnePlus VOOC devices" },
    ],
    shortDescription: "Realme Type-C VOOC cable for genuine VOOC fast charging.",
  },

  // ──────────────────────── Glass Protector (stock 50) ──────────────────────
  {
    name: "iPhone 13 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "iPhone 13 Tempered Glass",
    price: 249,
    sku: "GP-GEN-IP13",
    stock: 50,
    rating: 4.4,
    reviewCount: 212,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "iphone-13-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Scratch and drop resistant", "Oleophobic anti-fingerprint coating"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "iPhone 13" },
      { key: "Compatibility", value: "Apple iPhone 13" },
    ],
    shortDescription: "9H tempered glass screen protector for iPhone 13.",
  },
  {
    name: "iPhone 14 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "iPhone 14 Tempered Glass",
    price: 299,
    sku: "GP-GEN-IP14",
    stock: 50,
    rating: 4.5,
    reviewCount: 187,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "iphone-14-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Full edge-to-edge coverage", "HD transparent clarity"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "iPhone 14" },
      { key: "Compatibility", value: "Apple iPhone 14" },
    ],
    shortDescription: "9H tempered glass screen protector for iPhone 14.",
  },
  {
    name: "Samsung Galaxy S24 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "Samsung Galaxy S24 Tempered Glass",
    price: 299,
    sku: "GP-GEN-S24",
    stock: 50,
    rating: 4.5,
    reviewCount: 143,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "samsung-galaxy-s24-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Precise punch-hole cutout", "High touch sensitivity"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "Samsung Galaxy S24" },
      { key: "Compatibility", value: "Samsung Galaxy S24" },
    ],
    shortDescription: "9H tempered glass screen protector for Samsung Galaxy S24.",
  },
  {
    name: "Samsung Galaxy A55 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "Samsung Galaxy A55 Tempered Glass",
    price: 249,
    sku: "GP-GEN-A55",
    stock: 50,
    rating: 4.4,
    reviewCount: 98,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "samsung-galaxy-a55-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Anti-scratch protection", "Easy bubble-free installation"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "Samsung Galaxy A55" },
      { key: "Compatibility", value: "Samsung Galaxy A55" },
    ],
    shortDescription: "9H tempered glass screen protector for Samsung Galaxy A55.",
  },
  {
    name: "Redmi Note 13 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "Redmi Note 13 Tempered Glass",
    price: 199,
    sku: "GP-GEN-RN13",
    stock: 50,
    rating: 4.3,
    reviewCount: 176,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "redmi-note-13-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Full-screen protection", "Clear HD transparency"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "Redmi Note 13" },
      { key: "Compatibility", value: "Redmi Note 13 / 13 Pro" },
    ],
    shortDescription: "9H tempered glass screen protector for Redmi Note 13.",
  },
  {
    name: "Redmi Note 14 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "Redmi Note 14 Tempered Glass",
    price: 249,
    sku: "GP-GEN-RN14",
    stock: 50,
    rating: 4.4,
    reviewCount: 121,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    imageFile: "redmi-note-14-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Impact and scratch resistant", "Anti-fingerprint coating"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "Redmi Note 14" },
      { key: "Compatibility", value: "Redmi Note 14 / 14 Pro" },
    ],
    shortDescription: "9H tempered glass screen protector for Redmi Note 14.",
  },
  {
    name: "Realme 12 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "Realme 12 Tempered Glass",
    price: 199,
    sku: "GP-GEN-RM12",
    stock: 50,
    rating: 4.3,
    reviewCount: 87,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "realme-12-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Precise fit for Realme 12", "High clarity display"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "Realme 12" },
      { key: "Compatibility", value: "Realme 12 / 12 Pro" },
    ],
    shortDescription: "9H tempered glass screen protector for Realme 12.",
  },
  {
    name: "Vivo V40 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "Vivo V40 Tempered Glass",
    price: 249,
    discountPrice: 199,
    sku: "GP-GEN-VV40",
    stock: 50,
    rating: 4.4,
    reviewCount: 69,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "vivo-v40-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Edge-to-edge protection", "Anti-shatter film layer"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "Vivo V40" },
      { key: "Compatibility", value: "Vivo V40" },
    ],
    shortDescription: "9H tempered glass screen protector for Vivo V40.",
  },
  {
    name: "Oppo Reno 12 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "Oppo Reno 12 Tempered Glass",
    price: 249,
    sku: "GP-GEN-OR12",
    stock: 50,
    rating: 4.4,
    reviewCount: 73,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "oppo-reno-12-tempered-glass.webp",
    highlights: ["9H hardness tempered glass", "Precise cutout for curved display", "Smooth touch response"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "Oppo Reno 12" },
      { key: "Compatibility", value: "Oppo Reno 12 / 12 Pro" },
    ],
    shortDescription: "9H tempered glass screen protector for Oppo Reno 12.",
  },

  // ─────────────────────────── Earbuds (stock 20) ───────────────────────────
  {
    name: "Redmi Buds 6 Play",
    brandSlug: "redmi",
    categorySlug: "earbuds",
    model: "Buds 6 Play",
    price: 1799,
    sku: "EB-RD-B6P",
    stock: 20,
    rating: 4.4,
    reviewCount: 232,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "redmi-buds-6-play.webp",
    color: "Black",
    highlights: ["14.2mm dynamic drivers", "Up to 30 hours total playback", "Bluetooth 5.4 with low latency"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.4" },
      { key: "Battery", value: "Up to 30 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Redmi Buds 6 Play wireless earbuds with 14.2mm drivers and 30h battery.",
  },
  {
    name: "Realme Buds T110",
    brandSlug: "realme",
    categorySlug: "earbuds",
    model: "Buds T110",
    price: 1999,
    sku: "EB-RM-T110",
    stock: 20,
    rating: 4.4,
    reviewCount: 168,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "realme-buds-t110.webp",
    color: "Black",
    highlights: ["10mm bass boost drivers", "Up to 28 hours total playback", "ENC for clear calls"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.4" },
      { key: "Battery", value: "Up to 28 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Realme Buds T110 wireless earbuds with bass boost and ENC calls.",
  },
  {
    name: "Realme Buds Air 6",
    brandSlug: "realme",
    categorySlug: "earbuds",
    model: "Buds Air 6",
    price: 4799,
    sku: "EB-RM-A6",
    stock: 20,
    rating: 4.7,
    reviewCount: 254,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "realme-buds-air-6.webp",
    color: "White",
    highlights: ["50dB hybrid ANC", "12.4mm dynamic driver with deep bass", "Up to 40 hours with case", "Bluetooth 5.4"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.4" },
      { key: "Battery", value: "Up to 40 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Realme Buds Air 6 with 50dB hybrid ANC and 40h total battery.",
  },
  {
    name: "Baseus Bowie WM02",
    brandSlug: "baseus",
    categorySlug: "earbuds",
    model: "Bowie WM02",
    price: 1999,
    discountPrice: 1699,
    sku: "EB-BS-WM02",
    stock: 20,
    rating: 4.4,
    reviewCount: 145,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "baseus-bowie-wm02.webp",
    color: "Black",
    highlights: ["Semi-in-ear comfortable design", "10mm dynamic drivers", "Up to 25 hours with case"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.3" },
      { key: "Battery", value: "Up to 25 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Baseus Bowie WM02 semi-in-ear earbuds with comfortable all-day fit.",
  },
  {
    name: "Baseus Bowie E13",
    brandSlug: "baseus",
    categorySlug: "earbuds",
    model: "Bowie E13",
    price: 1799,
    sku: "EB-BS-E13",
    stock: 20,
    rating: 4.3,
    reviewCount: 112,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "baseus-bowie-e13.webp",
    color: "White",
    highlights: ["Clear bass-enhanced sound", "ENC noise reduction for calls", "Compact charging case"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.3" },
      { key: "Battery", value: "Up to 24 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Baseus Bowie E13 earbuds with ENC calling and compact case.",
  },
  {
    name: "Anker Soundcore R50i",
    brandSlug: "soundcore",
    categorySlug: "earbuds",
    model: "Soundcore R50i",
    price: 2599,
    sku: "EB-SC-R50I",
    stock: 20,
    rating: 4.5,
    reviewCount: 178,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "soundcore-r50i.webp",
    color: "Black",
    highlights: ["10mm drivers with BassUp sound", "Up to 30 hours with case", "IPX5 water resistance"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.3" },
      { key: "Battery", value: "Up to 30 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Anker Soundcore R50i earbuds with BassUp sound and IPX5 rating.",
  },
  {
    name: "Anker Soundcore A20i",
    brandSlug: "soundcore",
    categorySlug: "earbuds",
    model: "Soundcore A20i",
    price: 2899,
    sku: "EB-SC-A20I",
    stock: 20,
    rating: 4.6,
    reviewCount: 164,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "soundcore-a20i.webp",
    color: "White",
    highlights: ["Enhanced bass with soundcore app EQ", "Up to 28 hours with case", "AI-enhanced crystal-clear calls"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.3" },
      { key: "Battery", value: "Up to 28 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Anker Soundcore A20i earbuds with app EQ and AI clear calls.",
  },
  {
    name: "QCY T13 ANC",
    brandSlug: "qcy",
    categorySlug: "earbuds",
    model: "T13 ANC",
    price: 2399,
    sku: "EB-QCY-T13",
    stock: 20,
    rating: 4.5,
    reviewCount: 156,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    imageFile: "qcy-t13-anc.webp",
    color: "Black",
    highlights: ["Active noise cancellation", "7mm graphene drivers", "Up to 30 hours with case"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.3" },
      { key: "Battery", value: "Up to 30 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "QCY T13 ANC earbuds with active noise cancellation on a budget.",
  },
  {
    name: "Samsung Galaxy Buds FE",
    brandSlug: "samsung",
    categorySlug: "earbuds",
    model: "Galaxy Buds FE",
    price: 7999,
    sku: "EB-SM-BUDSFE",
    stock: 20,
    rating: 4.7,
    reviewCount: 221,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    imageFile: "samsung-galaxy-buds-fe.webp",
    color: "White",
    highlights: ["One UI optimized with Samsung ecosystem", "Active noise cancellation", "Up to 30 hours with case", "Comfortable wing-tip design"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.0" },
      { key: "Battery", value: "Up to 30 hours with case" },
      { key: "Compatibility", value: "Android, iOS & Windows" },
    ],
    shortDescription: "Samsung Galaxy Buds FE with ANC and seamless One UI integration.",
  },

  // ─────────────────────────── Smart Watch (stock 15) ────────────────────────
  {
    name: "Redmi Watch 5 Lite",
    brandSlug: "xiaomi",
    categorySlug: "smart-watch",
    model: "Redmi Watch 5 Lite",
    price: 5199,
    sku: "SW-XM-RW5L",
    stock: 15,
    rating: 4.6,
    reviewCount: 198,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "redmi-watch-5-lite.webp",
    color: "Black",
    highlights: ["AMOLED display", "Bluetooth calling", "SpO2, heart rate & sleep tracking", "5ATM water resistance"],
    specs: [
      { key: "Display", value: "AMOLED" },
      { key: "Battery", value: "Up to 14 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Redmi Watch 5 Lite with AMOLED display and Bluetooth calling.",
  },
  {
    name: "Mi Watch Lite",
    brandSlug: "xiaomi",
    categorySlug: "smart-watch",
    model: "Mi Watch Lite",
    price: 4999,
    sku: "SW-XM-MWL",
    stock: 15,
    rating: 4.4,
    reviewCount: 167,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "mi-watch-lite.webp",
    color: "Black",
    highlights: ["1.4\" color touch display", "11 sport modes", "5ATM water resistance", "Up to 9 days battery"],
    specs: [
      { key: "Display", value: "1.4\" TFT" },
      { key: "Battery", value: "Up to 9 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Mi Watch Lite with 11 sport modes and 5ATM water resistance.",
  },
  {
    name: "Realme Watch S2",
    brandSlug: "realme",
    categorySlug: "smart-watch",
    model: "Watch S2",
    price: 5999,
    sku: "SW-RM-WS2",
    stock: 15,
    rating: 4.5,
    reviewCount: 134,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "realme-watch-s2.webp",
    color: "Silver",
    highlights: ["1.32\" HD display", "Bluetooth calling", "SpO2 and heart rate tracking", "Up to 10 days battery"],
    specs: [
      { key: "Display", value: "1.32\" HD" },
      { key: "Battery", value: "Up to 10 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Realme Watch S2 with Bluetooth calling and 1.32\" HD display.",
  },
  {
    name: "Realme Watch 3",
    brandSlug: "realme",
    categorySlug: "smart-watch",
    model: "Watch 3",
    price: 4199,
    sku: "SW-RM-W3",
    stock: 15,
    rating: 4.4,
    reviewCount: 121,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "realme-watch-3.webp",
    color: "Black",
    highlights: ["1.8\" large display", "Bluetooth calling", "110+ sport modes", "5ATM water resistance"],
    specs: [
      { key: "Display", value: "1.8\" TFT" },
      { key: "Battery", value: "Up to 12 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Realme Watch 3 with a large 1.8\" display and Bluetooth calling.",
  },
  {
    name: "Haylou Solar Lite",
    brandSlug: "haylou",
    categorySlug: "smart-watch",
    model: "Solar Lite",
    price: 2999,
    sku: "SW-HL-SOLAR",
    stock: 15,
    rating: 4.3,
    reviewCount: 145,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "haylou-solar-lite.webp",
    color: "Black",
    highlights: ["1.43\" round dial", "14-day battery life", "Heart rate and sleep tracking", "IP68 water resistance"],
    specs: [
      { key: "Display", value: "1.43\" Round" },
      { key: "Battery", value: "Up to 14 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Haylou Solar Lite with a classic round dial and 14-day battery.",
  },
  {
    name: "Haylou RS4 Plus",
    brandSlug: "haylou",
    categorySlug: "smart-watch",
    model: "RS4 Plus",
    price: 3599,
    sku: "SW-HL-RS4P",
    stock: 15,
    rating: 4.4,
    reviewCount: 98,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    imageFile: "haylou-rs4-plus.webp",
    color: "Black",
    highlights: ["1.85\" AMOLED display", "Bluetooth calling", "Precise health tracking", "Up to 15 days battery"],
    specs: [
      { key: "Display", value: "1.85\" AMOLED" },
      { key: "Battery", value: "Up to 15 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Haylou RS4 Plus with AMOLED display and Bluetooth calling.",
  },
  {
    name: "Kieslect Calling Watch KR",
    brandSlug: "kieslect",
    categorySlug: "smart-watch",
    model: "Calling Watch KR",
    price: 3999,
    discountPrice: 3399,
    sku: "SW-KS-CWKR",
    stock: 15,
    rating: 4.4,
    reviewCount: 88,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "kieslect-calling-watch-kr.webp",
    color: "Black",
    highlights: ["Loud clear Bluetooth calling", "1.39\" HD display", "Battery up to 12 days", "Kieslect app support"],
    specs: [
      { key: "Display", value: "1.39\" HD" },
      { key: "Battery", value: "Up to 12 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Kieslect Calling Watch KR with clear Bluetooth calling and 1.39\" display.",
  },
  {
    name: "Amazfit Bip 5",
    brandSlug: "amazfit",
    categorySlug: "smart-watch",
    model: "Bip 5",
    price: 6999,
    sku: "SW-AZ-BIP5",
    stock: 15,
    rating: 4.6,
    reviewCount: 173,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "amazfit-bip-5.webp",
    color: "Black",
    highlights: ["1.91\" ultra-large display", "Bluetooth calling", "120+ sport modes", "Up to 10 days battery"],
    specs: [
      { key: "Display", value: "1.91\" TFT" },
      { key: "Battery", value: "Up to 10 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Amazfit Bip 5 with a 1.91\" display and 120+ sport modes.",
  },
  {
    name: "Samsung Galaxy Fit3",
    brandSlug: "samsung",
    categorySlug: "smart-watch",
    model: "Galaxy Fit3",
    price: 5999,
    sku: "SW-SM-GF3",
    stock: 15,
    rating: 4.5,
    reviewCount: 132,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    imageFile: "samsung-galaxy-fit3.webp",
    color: "Black",
    highlights: ["1.6\" AMOLED display", "Advanced sleep and heart tracking", "Up to 13 days battery", "Samsung Health integration"],
    specs: [
      { key: "Display", value: "1.6\" AMOLED" },
      { key: "Battery", value: "Up to 13 days" },
      { key: "Compatibility", value: "Android (Samsung Health)" },
    ],
    shortDescription: "Samsung Galaxy Fit3 with AMOLED display and Samsung Health tracking.",
  },

  // ─────── Homepage featured picks — newest, §11 (2 featured per category) ───
  {
    name: "Realme Buds 2 Wired",
    brandSlug: "realme",
    categorySlug: "earphone",
    model: "Buds 2 Wired",
    price: 699,
    sku: "EP-RM-B2W",
    stock: 30,
    rating: 4.6,
    reviewCount: 175,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "realme-buds-2-wired.webp",
    color: "Black",
    highlights: ["11.2mm bass boost driver", "Hyper-bass sound signature", "Built-in mic with remote control"],
    specs: [
      { key: "Connector Type", value: "3.5mm Jack" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Realme Buds 2 wired earphones with 11.2mm bass boost drivers.",
  },
  {
    name: "Baseus Bipow Digital Display 10000mAh",
    brandSlug: "baseus",
    categorySlug: "power-bank",
    model: "Bipow Digital Display 10000mAh",
    price: 1799,
    sku: "PB-BS-BIPOW",
    stock: 20,
    rating: 4.6,
    reviewCount: 268,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    imageFile: "baseus-bipow-10000mah.webp",
    color: "Black",
    highlights: ["10000mAh capacity", "Fast charging support", "Dual USB output", "LED battery percentage display", "Compact travel-friendly design"],
    specs: [
      { key: "Battery Capacity", value: "10000mAh" },
      { key: "Output", value: "Dual USB 5V/2.1A" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Baseus Bipow 10000mAh fast charging power bank with digital battery display.",
  },
  {
    name: "Anker PowerLine Select+ USB-C Cable",
    brandSlug: "anker",
    categorySlug: "usb-cable",
    model: "PowerLine Select+ USB-C",
    price: 849,
    sku: "UC-ANK-PLSEL",
    stock: 40,
    rating: 4.7,
    reviewCount: 245,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "anker-powerline-select-plus-usb-c.webp",
    color: "Black",
    highlights: ["Tested to last 25,000 bends", "Fast charging up to 60W", "Premium braided finish"],
    specs: [
      { key: "Type", value: "USB-C to USB-C" },
      { key: "Length", value: "1.8m" },
      { key: "Compatibility", value: "USB-C phones, tablets & laptops" },
    ],
    shortDescription: "Anker PowerLine Select+ USB-C cable, built to survive 25,000 bends.",
  },
  {
    name: "iPhone 15 Tempered Glass",
    brandSlug: "generic",
    categorySlug: "glass-protector",
    model: "iPhone 15 Tempered Glass",
    price: 349,
    sku: "GP-GEN-IP15",
    stock: 50,
    rating: 4.6,
    reviewCount: 264,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    imageFile: "iphone-15-tempered-glass.webp",
    highlights: ["9H hardness with shock absorption", "Precise cutout for Dynamic Island", "Anti-fingerprint oleophobic layer"],
    specs: [
      { key: "Type", value: "Tempered Glass" },
      { key: "Device", value: "iPhone 15" },
      { key: "Compatibility", value: "Apple iPhone 15" },
    ],
    shortDescription: "9H tempered glass screen protector for iPhone 15.",
  },
  {
    name: "Redmi Buds 5",
    brandSlug: "redmi",
    categorySlug: "earbuds",
    model: "Buds 5",
    price: 2899,
    sku: "EB-RD-B5",
    stock: 20,
    rating: 4.6,
    reviewCount: 341,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    imageFile: "redmi-buds-5.webp",
    color: "White",
    highlights: ["46dB active noise cancellation", "12.4mm coated dynamic driver", "Up to 40 hours with case", "Google Fast Pair support"],
    specs: [
      { key: "Connectivity", value: "Bluetooth 5.3" },
      { key: "Battery", value: "Up to 40 hours with case" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Redmi Buds 5 with 46dB active noise cancellation and 40h battery life.",
  },
  {
    name: "Redmi Watch 5 Active",
    brandSlug: "xiaomi",
    categorySlug: "smart-watch",
    model: "Redmi Watch 5 Active",
    price: 4499,
    sku: "SW-XM-RW5A",
    stock: 15,
    rating: 4.6,
    reviewCount: 289,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    imageFile: "redmi-watch-5-active.webp",
    color: "Black",
    highlights: ["2.0\" HD display", "Bluetooth calling support", "140+ sport modes", "Up to 18 days battery life"],
    specs: [
      { key: "Display", value: "2.0\" HD" },
      { key: "Battery", value: "Up to 18 days" },
      { key: "Compatibility", value: "Android & iPhone" },
    ],
    shortDescription: "Redmi Watch 5 Active with Bluetooth calling, 2\" HD display and 18-day battery.",
  },
];

/** Slug derived from the image filename (docs say: generate slugs automatically). */
export function slugFor(p: CatalogProduct): string {
  return p.imageFile.replace(/\.(webp|png|jpe?g)$/i, "");
}
